// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'api_exception.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'api_exception.g.dart';

@freezed
class ApiException with _$ApiException {
  const factory ApiException({
    required String message,
    int? code,
    int? statusCode,
  }) = _ApiException;

  factory ApiException.fromJson(Map<String, Object?> json) =>
      _$ApiExceptionFromJson(json);
}
